# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qu798vQMsP4fqBk_ecStg55yQuLP_vVZ
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
filename = list(uploaded.keys())[0]  # automatically grabs whatever filename Colab saved it as
df = pd.read_csv(filename)
df.head()

X = df.drop(columns=['Churn'])
churn_labels = df['Churn']  # keep this for later, don't use it in clustering

X.info()

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K_range = range(1, 11)

for k in K_range:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    km.fit(X)
    inertia.append(km.inertia_)

plt.figure(figsize=(8,5))
plt.plot(K_range, inertia, marker='o')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia (WCSS)')
plt.title('Elbow Method for Optimal K')
plt.xticks(K_range)
plt.grid(True)
plt.show()

from sklearn.metrics import silhouette_score

sil_scores = []
for k in range(2, 11):
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    labels = km.fit_predict(X)
    sil_scores.append(silhouette_score(X, labels))

plt.plot(range(2, 11), sil_scores, marker='o', color='green')
plt.xlabel('K')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score by K')
plt.grid(True)
plt.show()

optimal_k = 4

kmeans = KMeans(n_clusters=optimal_k, init='k-means++', n_init=10, random_state=42)
df['Cluster'] = kmeans.fit_predict(X)

df['Cluster'].value_counts().sort_index()

from sklearn.decomposition import PCA
import seaborn as sns

pca = PCA(n_components=2)
components = pca.fit_transform(X)
df['PCA1'] = components[:, 0]
df['PCA2'] = components[:, 1]

plt.figure(figsize=(9,6))
sns.scatterplot(data=df, x='PCA1', y='PCA2', hue='Cluster', palette='Set2', alpha=0.7)
plt.title('Customer Segments (K-Means Clusters, PCA-reduced)')
plt.show()

print("Explained variance ratio:", pca.explained_variance_ratio_)
print("Total variance explained:", pca.explained_variance_ratio_.sum())

pd.set_option('display.width', 200)
pd.set_option('display.max_columns', 20)

# Average value of each feature per cluster
cluster_profile = df.groupby('Cluster')[X.columns].mean().round(3)
print(cluster_profile)

print("\nChurn rate by cluster:")
print(df.groupby('Cluster')['Churn'].mean().round(3))

from google.colab import files

df.to_csv('clustered_customer_data.csv', index=False)
files.download('clustered_customer_data.csv')

